name: pubspec_dependency_sorter
version: 1.0.6
Author: Danche Nganga <ngangadanche@gmail.com>
homepage: https://github.com/danchengash/pubspec-dependency-sorter
description: helps sort flutter,dart pubspec.yaml dependecies alphabetically.
environment: 
  sdk: '>=2.17.0 <4.0.0'
  # flutter: '>=1.17.0'
dependencies: 
  logger: ^2.0.1
  pubspec: ^2.3.0
  flutter: 
    sdk: flutter
  yaml_writer: ^2.0.0
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter